# dbt_project.yml
name: 'medical_warehouse'
version: '1.0.0'
config-version: 2

profile: 'medical_warehouse' # This MUST match the name in your profiles.yml

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  medical_warehouse:
    staging:
      materialized: view    # Staging is usually views
    marts:
      materialized: table   # Marts (Facts/Dims) are usually tables