version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_name
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_name